const taskfile=require('./util')
console.log("Area of Square",+taskfile.square(5))
console.log("Area of Circle",+taskfile.circle(8))
console.log("Area of Triangle",+taskfile.triangle(5,6))
console.log("Area of Rectangle",+taskfile.Rectangle(5,4))